### ISSUE TITLE
test

### ISSUE THREAD

**Issue by wmioduszewski** [wmioduszewski/Remote-pairing#3]
asd

![image](https://user-images.githubusercontent.com/11396397/31983546-f96dd0c2-b95d-11e7-9482-cfc73423c98d.png)

**Comment by anselmos** [comment]
^^ testujesz issiues na githubie ? moze moge Ci jakos pomoc ?

śr., 25 paź 2017 o 08:24 użytkownik Wojciech Mioduszewski <
notifications@github.com> napisał:

**Comment by marmiod1** [comment]
dostałam wiadomość od Ciebie, świadomie? ;) 
 
W dniu 2017-10-25 08:24:57 użytkownik Wojciech Mioduszewski <notifications@github.com> napisał:
asd

**Comment by wmioduszewski** [comment]
niestety nieświadmomie :)

2017-10-25 9:56 GMT+02:00 marmiod1 <notifications@github.com<mailto:notifications@github.com>>:
dostałam wiadomość od Ciebie, świadomie? ;)

W dniu 2017-10-25 08:24:57 użytkownik Wojciech Mioduszewski <notifications@github.com<mailto:notifications@github.com>> napisał:
asd

**Comment by marmiod1** [comment]
zatem dobrze że nic obraźliwego ;) 
 
W dniu 2017-10-25 10:01:48 użytkownik Wojciech Mioduszewski <notifications@github.com> napisał:
niestety nieświadmomie :)
2017-10-25 9:56 GMT+02:00 marmiod1 <notifications@github.com<mailto:notifications@github.com>>:
dostałam wiadomość od Ciebie, świadomie? ;)
W dniu 2017-10-25 08:24:57 użytkownik Wojciech Mioduszewski <notifications@github.com<mailto:notifications@github.com>> napisał:
asd
